apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registry-api-role
rules:
- apiGroups:
  - toolhive.stacklok.dev
  resources:
  - mcpservers
  verbs:
  - get
  - list
  - watch